### ISSUE TITLE
kinds triggers bad argument to ipairs

### ISSUE THREAD

**Issue by jemag** [Allaman/kustomize.nvim#60]
After building the manifests for an ArgoCD installation, if I run the `:KustomizeListKinds` in that buffer, I get the following error:
![image](https://github.com/user-attachments/assets/c5c4f568-97e7-458a-8049-44f5738e2c32)
Where it seems the `containsAnyOf` function is expecting a table.

I took a subset of the generated yaml that should be able to reproduce the error. Please excuse the overly long yaml:
https://gist.github.com/jemag/b2cd757dfd84d1fd381cd62fa3613913

**Comment by Allaman** [comment]
Hello, I can't reproduce the error with the "minimal" 😉 not working example you provided 
<img width="962" alt="image" src="https://github.com/user-attachments/assets/c946d639-971d-49d8-b18d-0532a66725b3">

**Comment by jemag** [comment]
Interesting. I will make sure to reproduce with a minimal neovim config, just to be sure there isn't any weird interaction from other plugins. I'll update once I do

**Comment by Allaman** [comment]
If you have not your own, you could use [this](https://github.com/Allaman/nvim/blob/main/minimal_init_lazy.lua) template (that I stole from Folke 😆 ) and run `nvim -u minimal_init_lazy.lua`

**Comment by Allaman** [comment]
@jemag meanwhile I stumbled over this bug too 😞

**Comment by Allaman** [comment]
A very strange bug. I don't understand why this did not occur earlier for me 😞 Should be solved now

**Comment by jemag** [comment]
Sorry for the long delay, was on vacation. Seems to be working great now, thank you!
