### ISSUE TITLE
enable_key_mappings = false should disable telescope loclist keybind

### ISSUE THREAD

**Issue by jemag** [Allaman/kustomize.nvim#63]
I currently have disabled all the default keybindings, however the `Telescope loclist` does get defined when telescope module is available.

The current keybind `<leader>kt` conflicts with another one I have.

It would be nice if that keybind could be disabled as well.

**Comment by Allaman** [comment]
Good catch! Please check out the new version

**Comment by jemag** [comment]
works well now, thanks!
